import Sidebar from "@/components/Sidebar";
import { CssBaseline } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <CssBaseline />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </>
  );
}
